// Generated by gencpp from file theconstruct_msgs/RLExperimentInfo.msg
// DO NOT EDIT!


#ifndef THECONSTRUCT_MSGS_MESSAGE_RLEXPERIMENTINFO_H
#define THECONSTRUCT_MSGS_MESSAGE_RLEXPERIMENTINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace theconstruct_msgs
{
template <class ContainerAllocator>
struct RLExperimentInfo_
{
  typedef RLExperimentInfo_<ContainerAllocator> Type;

  RLExperimentInfo_()
    : episode_number(0)
    , episode_reward(0.0)  {
    }
  RLExperimentInfo_(const ContainerAllocator& _alloc)
    : episode_number(0)
    , episode_reward(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _episode_number_type;
  _episode_number_type episode_number;

   typedef float _episode_reward_type;
  _episode_reward_type episode_reward;





  typedef boost::shared_ptr< ::theconstruct_msgs::RLExperimentInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::theconstruct_msgs::RLExperimentInfo_<ContainerAllocator> const> ConstPtr;

}; // struct RLExperimentInfo_

typedef ::theconstruct_msgs::RLExperimentInfo_<std::allocator<void> > RLExperimentInfo;

typedef boost::shared_ptr< ::theconstruct_msgs::RLExperimentInfo > RLExperimentInfoPtr;
typedef boost::shared_ptr< ::theconstruct_msgs::RLExperimentInfo const> RLExperimentInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::theconstruct_msgs::RLExperimentInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::theconstruct_msgs::RLExperimentInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::theconstruct_msgs::RLExperimentInfo_<ContainerAllocator1> & lhs, const ::theconstruct_msgs::RLExperimentInfo_<ContainerAllocator2> & rhs)
{
  return lhs.episode_number == rhs.episode_number &&
    lhs.episode_reward == rhs.episode_reward;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::theconstruct_msgs::RLExperimentInfo_<ContainerAllocator1> & lhs, const ::theconstruct_msgs::RLExperimentInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace theconstruct_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::theconstruct_msgs::RLExperimentInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::theconstruct_msgs::RLExperimentInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::theconstruct_msgs::RLExperimentInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::theconstruct_msgs::RLExperimentInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::theconstruct_msgs::RLExperimentInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::theconstruct_msgs::RLExperimentInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::theconstruct_msgs::RLExperimentInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "117729220546455cc216a7df0b6e91d0";
  }

  static const char* value(const ::theconstruct_msgs::RLExperimentInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x117729220546455cULL;
  static const uint64_t static_value2 = 0xc216a7df0b6e91d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::theconstruct_msgs::RLExperimentInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "theconstruct_msgs/RLExperimentInfo";
  }

  static const char* value(const ::theconstruct_msgs::RLExperimentInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::theconstruct_msgs::RLExperimentInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 episode_number\n"
"float32 episode_reward\n"
;
  }

  static const char* value(const ::theconstruct_msgs::RLExperimentInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::theconstruct_msgs::RLExperimentInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.episode_number);
      stream.next(m.episode_reward);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RLExperimentInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::theconstruct_msgs::RLExperimentInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::theconstruct_msgs::RLExperimentInfo_<ContainerAllocator>& v)
  {
    s << indent << "episode_number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.episode_number);
    s << indent << "episode_reward: ";
    Printer<float>::stream(s, indent + "  ", v.episode_reward);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THECONSTRUCT_MSGS_MESSAGE_RLEXPERIMENTINFO_H
